/**
 * Workspace warning report (issue #121).
 *
 * `scan-skills` regenerates SHIELDCORTEX_WARNINGS.md in the workspace so the
 * file always matches the live scanner: when nothing is flagged the stale file
 * is removed; when something is flagged it is rewritten with the current set.
 *
 * The format mirrors the marker the cortex-memory hook already emits at
 * bootstrap, so downstream consumers see one consistent document.
 */

import { existsSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const WARNINGS_FILENAME = 'SHIELDCORTEX_WARNINGS.md';

export interface FlaggedSkill {
  skillName: string;
  path: string;
  riskLevel: string;
  summary: string;
}

/**
 * Render the warnings markdown for a non-empty set of flagged skills.
 * (Callers should remove the file instead of writing an "all clear" doc.)
 */
export function generateWarningsMarkdown(flagged: FlaggedSkill[]): string {
  const lines = flagged
    .map((f) => `- **${f.skillName}** (\`${f.path}\`) — ${f.riskLevel}: ${f.summary}`)
    .join('\n');

  return [
    '# ShieldCortex Security Warning',
    '',
    'The following installed skills/hooks have been flagged as potentially unsafe:',
    '',
    lines,
    '',
    'Review each file. If a file is legitimate and you want to stop it being',
    'flagged, accept it (re-flags automatically if the file later changes):',
    '',
    '```bash',
    'shieldcortex scan-skill <path> --accept',
    '```',
    '',
    'Generated by `shieldcortex scan-skills`.',
    '',
  ].join('\n');
}

/**
 * Regenerate the workspace warnings file so it always matches the live scanner.
 *
 * - `flagged` non-empty → write/overwrite the report.
 * - `flagged` empty     → remove any stale report.
 *
 * Never throws — filesystem errors are swallowed (best-effort reporting).
 * Returns the action taken, for logging/tests.
 */
export function writeWarningsFile(
  workspaceDir: string,
  flagged: FlaggedSkill[],
): 'written' | 'removed' | 'absent' {
  const filePath = join(workspaceDir, WARNINGS_FILENAME);
  try {
    if (flagged.length > 0) {
      writeFileSync(filePath, generateWarningsMarkdown(flagged), 'utf-8');
      return 'written';
    }
    if (existsSync(filePath)) {
      unlinkSync(filePath);
      return 'removed';
    }
    return 'absent';
  } catch {
    return 'absent';
  }
}
