export const GUARD_SIGNAL_VOCABULARY: readonly string[];
export const EVENT_ENUM: readonly string[];
export const DENIAL_OUTCOMES: readonly string[];
export const WARNING_OUTCOMES: readonly string[];
export const RETRY_OUTCOMES: readonly string[];
export const OUTCOME_ENUM: readonly string[];
export const NOTIFY_STATUS_ENUM: readonly string[];
export const DELIVERY_CLAIM_STATUSES: readonly string[];
export const DELIVERY_CHANNEL_ENUM: readonly string[];
export const SEVERITY_ENUM: readonly string[];
export const TOOL_ENUM: readonly string[];
export const OTHER: 'other';
export const REDACTED_SIGNAL_LABEL: '<signal-outside-vocabulary-redacted>';
export function publicEvent(v: unknown): string;
export function publicOutcome(v: unknown): string;
export function publicNotifyStatus(v: unknown): string;
export function publicChannel(v: unknown): string;
export function publicSeverity(v: unknown): string;
export function publicTool(v: unknown): string;
export function isVocabularySignal(s: unknown): s is string;
export function publicSignalName(s: unknown): string;
export function validateNotify(row: { notify?: unknown }): { ok: true; status: string | null; channel: string | null } | { ok: false; reason: string };
